export enum Actions {
  START_RECORDING = "START_RECORDING",
  STOP_RECORDING = "STOP_RECORDING",
  SAVE_RECORD = "SAVE_RECORD",
  PLAY_LIVE = "PLAY_LIVE",
  PLAY_RECORD = "PLAY_RECORD",
  SET_MOVEMENTS = "SET_MOVEMENTS",
  SET_LIVE_OFF = "SET_LIVE_OFF",
}
